enum PurposeType {
  HOME_RENOVATION = 'HOME_RENOVATION',
  EDUCATION = 'EDUCATION',
  MEDICAL = 'MEDICAL',
  BUSINESS_EXPANSION = 'BUSINESS_EXPANSION',
  WORKING_CAPITAL = 'WORKING_CAPITAL',
  OTHER = 'OTHER'
}

export default PurposeType;
